name: Sync Fork
on:
  schedule:
    - cron: '0 * * * *' # 每小时运行
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Sync with upstream
      run:
        git remote add upstream https://github.com/LmeSzinc/AzurLaneAutoScript.git
        git fetch upstream
        git checkout master
        git merge upstream/master
        git push origin master